// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs8FIU0z2ykYmIWuCHYXri2VvcOrK6QRI',
    appId: '1:1058827566369:web:23f79bd66faf21073b1260',
    messagingSenderId: '1058827566369',
    projectId: 'fitrix31',
    authDomain: 'fitrix31.firebaseapp.com',
    storageBucket: 'fitrix31.firebasestorage.app',
    measurementId: 'G-KMCX4W6YD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwZhxlfu9UB7pDgCRnqQ5oyGcXOvpC2GE',
    appId: '1:1058827566369:android:f8d2fc6c9e4df4423b1260',
    messagingSenderId: '1058827566369',
    projectId: 'fitrix31',
    storageBucket: 'fitrix31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg4bSsBWdaEBXXoS8bcJjH11CkddP6VV0',
    appId: '1:1058827566369:ios:1e2249304ad0aea63b1260',
    messagingSenderId: '1058827566369',
    projectId: 'fitrix31',
    storageBucket: 'fitrix31.firebasestorage.app',
    iosBundleId: 'com.fitrix.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg4bSsBWdaEBXXoS8bcJjH11CkddP6VV0',
    appId: '1:1058827566369:ios:30be3b76c89f57953b1260',
    messagingSenderId: '1058827566369',
    projectId: 'fitrix31',
    storageBucket: 'fitrix31.firebasestorage.app',
    iosBundleId: 'com.example.fitrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs8FIU0z2ykYmIWuCHYXri2VvcOrK6QRI',
    appId: '1:1058827566369:web:b742bc107c4809b93b1260',
    messagingSenderId: '1058827566369',
    projectId: 'fitrix31',
    authDomain: 'fitrix31.firebaseapp.com',
    storageBucket: 'fitrix31.firebasestorage.app',
    measurementId: 'G-V7G7JSQRP1',
  );
}
